spring:
  application:
    name: education-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/education_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:2w3a236fdj!}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 25
          lob:
            non_contextual_creation: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437} # Минимум 256 бит для HS256
  expiration: 24 # Часы
  refresh-expiration: 168 # 7 дней
  clock-skew-seconds: 60

# Application Custom Properies
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

logging:
  level:
    root: INFO
    org.bm.service.education: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
